### ISSUE TITLE
Document CLI API in Markdown so that it can be published to https://pharo-project.github.io/pharo-launcher/

### ISSUE THREAD

**Issue by demarey** [axlgithub/CommandLineLauncher#4]
ex: https://github.com/pharo-project/pharo-launcher/blob/dev/docs/commands.md

**Comment by Bajger** [comment]
@demarey Hi Christophe! I wonder what level of detail we would like to have this for cmd line description. Few questions to this:
1) Can I continue/proceed from https://github.com/axlgithub/CommandLineLauncher/blob/dev/PharoLauncherCmdLine-description.md
- to remove unnecessary stuff, just overview table
- And then example usages for each command, list of parameters, flags, and example output?

2) are we ok with `launcher -> subject -> verb`flow? I recall our last discussion (also with @axlgithub ), where there was consideration from you regarding flow `launcher -> verb -> subject`. I'm wondering, if we have an agreement on this (since code from me follows subject->verb approach). My personal preference is to go with 1st approach, since I see 1st level (subject->verb) as less verbose (we have just few subjects). Some of verbs are not relevant for some of subjects. On the other hand, of course we would have some duplications (I counted 3 duplications: list, info, delete. And rest is subject specific) of verbs in 2nd level. Please give a final verdict. I guess it is not super important, but would be much harder to rewrite code later.  

Examples:
subject-verb approach:
```
pharoLauncher image create templateName
pharoLanucher vm update vmName
pharoLauncher image info imageName
pharoLauncher image list
```
verb-subject approach
```
pharoLauncher delete image imageName
pharoLauncher copy image imageName newImageName
pharoLauncher update vm vmName
```

**Comment by demarey** [comment]
Hi David!
Here are some answers:

1. yes, it is a very good start. I think _Overview of Pharo Laucher commands_ and _Description of Pharo Launcher commands_ sections could be included as they are now in the docs under a command-line chapter. First 2 sections could be kept in the existing document until the project is ready. I think having a usage example of each command would be nice.
2. ok for `launcher -> subject -> verb`. I have a little preference for verb first but subject first is also nice and is already implemented, so let's keep it.

Also, to keep you informed, we will define a configuration file in Ston format where user preferences will be kept (e.g. images folder, VMs folder, etc). This way, the pharo image will be stateless

**Comment by Bajger** [comment]
@demarey @axlgithub Hi guys! I think issue can be closed now, since Alex already did that: https://github.com/PharoLauncherCmdLine/CommandLineLauncher/blob/doc-cmd-line/docs/commands-cmd-line.md
Is it ok to close issue now? Or you want to merge with ML and then close. Thanks!

**Comment by demarey** [comment]
ok  to close
